build:
 make -C libcore
 make -C libui
 make -C libnet
 make -C libcomm
 make -C libmedia

clean:
 make -C libcore  clean
 make -C libui    clean
 make -C libnet   clean
 make -C libcomm  clean
 make -C libmedia clean

install:
 make -C libcore  install
 make -C libui    install
 make -C libnet   install
 make -C libcomm  install
 make -C libmedia install
