build:
 make -C libcore
 make -C libui
 make -C libmedia

clean:
 make -C libcore  clean
 make -C libui    clean
 make -C libmedia clean

install:
 make -C libcore  install
 make -C libui    install
 make -C libmedia install
 install inc lib ${DESTDIR}
